name: acceptance-tests
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/acctests.yml
      - illumio-core/*.go
      - scripts/acccoveragecheck.sh
jobs:
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Install Dependencies
        run: apt update && apt install bc -y
      -
        name: Run Acc. Tests
        run: sh scripts/acccoveragecheck.sh
        # env:
          # Required to run acc tests successfully
          # TODO set below env vars in secrets
          # TF_ACC: 1
          # ILLUMIO_PCE_HOST: ${{ secrets.ACC_TEST_ILLUMIO_PCE_HOST }}
          # ILLUMIO_API_KEY_USERNAME: ${{ secrets.ACC_TEST_ILLUMIO_API_KEY_USERNAME }}
          # ILLUMIO_API_KEY_SECRET: ${{ secrets.ACC_TEST_ILLUMIO_API_KEY_SECRET }}
          # ILLUMIO_AES_GCM_KEY: ${{ secrets.ACC_TEST_ILLUMIO_AES_GCM_KEY }}